name: Run Crypto Application

on:
  schedule:
    - cron: '0 9 * * 1'  # Voer uit elke maandag om 09:00 UTC
    - cron: '50 22 * * 6'  # Voer uit elke zaterdag om 22:50 UTC
    - cron: '00 9 * * 7'  # Voer uit elke zondag om 09:00 UTC
  workflow_dispatch:  # Maakt het mogelijk om de workflow handmatig te starten via GitHub Actions

jobs:
  run-application:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Kies de Python-versie die je nodig hebt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance ta pandas python-telegram-bot

    - name: Run application
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python app.py  # Vervang 'your_script_name.py' door de naam van je script
